### PR TITLE
Allow mixed case in DSN (closes #176)

### LINKED ISSUE #176: from_DSN won't work with upper case passwords
Hello,

If the password given in the dsn string to InfluxDBClient.from_DSN contains some upper case letters, then subsequent queries on the client will fail with:
```
  File "/usr/local/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 419, in query
    chunked=chunked)
  File "/usr/local/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 447, in _query
    expected_response_code=200
  File "/usr/local/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 255, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.influxdb08.client.InfluxDBClientError: 401: Invalid username/password
```

Good practice for passwords is to mix lower and upper cases.
I guess other params like username and database name in the dsn could also have this problem if they are case sensitive as well. I did not test them.

For the moment it can be solved by giving the password as an extra parameter to from_DSN. But it could confuse other users and take them a while to understand.

Cheers,
Axel

### PR DESCRIPTION
**Pull request by ReAzem**
@cannium What do you think?

That would close #176

### CODE REVIEW

**Comment by ChristopherRabotin** [comment]
I think the reason why I converted this to lower case is to make sure that the protocol is correctly identified even if it's given in uppercase. Maybe would it be worth doing the protocol check with the lowercase version of the DSN.

**Comment by ReAzem** [comment]
Oh. I pinged the wrong guy.  My bad :) 

You are right,  it would be a good idea convert the case to check for the protocol.

I'll give a try tomorrow.

**Comment by cannium** [comment]
@ReAzem No problem.
The scheme part(`https+influxdb`) should be converted to lower case to check, and other parts(like username, password) are case sensitive, in my opinion.

**Comment by ReAzem** [comment]
Looks like it already worked. ``urlparse`` does the work for us.

**Comment by ReAzem** [comment]
@ChristopherRabotin Any feedback? Good to merge?

**Comment by ChristopherRabotin** [comment]
@ReAzem looks good, nothing to add. Thanks for asking!

**Comment by ReAzem** [comment]
Thank you :)!

**Pull request merged**
