### PR TITLE
Update vs server 0.9.0 rc17 1 g947c776

### PR DESCRIPTION
**Pull request by gst**
Return format of "show databases" changed. Adapted tests for that.

### CODE REVIEW

**Comment by ReAzem** [comment]
I'll be waiting for Travis.  Thanks :)

**Comment by gst** [comment]
I've directly seen that by having pulled my server master branch, builded & installed the deb and simply relaunched all the client tests and bam thx to the client_test_with_server.py ; so its practical use ;)

**Comment by gst** [comment]
don't get why https://travis-ci.org/influxdb/influxdb-python/jobs/56423060 failed ..

**Comment by ReAzem** [comment]
I think Travis is drunk. I have restarted the job.

**Comment by ReAzem** [comment]
Merged 15b652f2bf50db892292b0220b30d6ff93d7ad26.

**Pull request closed without merging**
