### PR TITLE
Fix issue 237

### PR DESCRIPTION
**Pull request by georgijd**
This should enable the cluster client to properly switch databases and user credentials for all clients in the cluster, not just a random one. It doesn't look pretty and actually I'd like to suggest an alternative implementation of the InfluxDBClusterClient which will actually inherit the InfluxDBClient and instead of maintaining a list of InfluxDBClients, we can just keep the list of (host, port) tuples and alternate those on each request. This way we win a few things:
- Less memory usage, obviously. There's no need to create 3 InfluxDBClient objects when we can get away with a single one;
- We get access to all attributes of the InfluxDBClient  (not just the callable ones);
- Docstrings available for all methods. It also means that auto-completion will be available for developers;
- Easier maintenance and avoiding bugs similar to this one.

Since some users of the library might be using the `clients` attribute of the cluster client current implementation, we can make the new one backwards compatible by having a list with only one element (self) as the `clients` attribute, i.e. ```self.clients = [self]```

@aviau , @gst, @areski , any thoughts on that?

### CODE REVIEW

**Comment by gst** [comment]
seems totally legit to me, so +1 :)
Have you a branch already made with what you propose ?

**Comment by georgijd** [comment]
Hi, 
I haven't written anything yet, but I can come up with an initial draft tonight :)

**Comment by aviau** [comment]
Thank you @georgijd

**Comment by georgijd** [comment]
Hey guys, sorry for the delay, it's been a busy week :)
You can check out what I've come up with here: https://github.com/georgijd/influxdb-python/commit/e25576f324c225ff37fd12b1e190b314b8514b45

**Comment by aviau** [comment]
@georgijd Can you transfer this onto this PR?

**Comment by aviau** [comment]
As far as I understand, this is fixed in #253

**Pull request closed without merging**
