### PR TITLE
Create db only if doesn't exist yet

### PR DESCRIPTION
**Pull request by slomek**
This is a follow-up of https://github.com/influxdb/influxdb-python/pull/274

### CODE REVIEW

**Comment by aviau** [comment]
@slomek Have you taken a look at the tests failures?

**Comment by slomek** [comment]
Yep, I've had some issues with running them locally. I've changed the default behaviour to create dbs if they do not exist, but also added a flag if you want to fail anyway (and not to delete one of your tests). This breaks backward compatibility a little, but in my opinion it would be better this way.

**Comment by slomek** [comment]
@aviau Can you merge this or is there anything else I should fix first?

**Comment by aviau** [comment]
@slomek I am sorry for the long response time. Can you please switch the default around? Some people may rely on this throwing exceptions and I think its a saner default.

I will merge right after!

**Comment by slomek** [comment]
No problem, @aviau. Take a look on it now.

**Comment by aviau** [comment]
Thanks!!

**Pull request merged**
