### PR TITLE
Remove dict comprehension for older python

### PR DESCRIPTION
**Pull request by cannium**
dict comprehension is introduced in python 2.7 and doesn't work on 2.6 or older

### CODE REVIEW

**Comment by ReAzem** [comment]
Is this the only thing that is not compatible 2.6? I have never tested the lib with python2.6. Is it really worth supporting?

**Comment by cannium** [comment]
I found it when I tried to pack an RPM for centos6.5 and python2.6 complained about it doesn't know how to handle the syntax. So I could safely assume that's the only syntax not compatible with 2.6. For other parts as far as I've tested, runs well with 2.6.

**Comment by ReAzem** [comment]
Alright then!  Thank your for contributing :)

**Comment by ReAzem** [comment]
Merged Remove dict comprehension for older python #150

**Pull request merged**
