### PR TITLE
Correctly check that the given serie name has the correct type

### PR DESCRIPTION
**Pull request by gst**
type(b''.decode()) should give unicode or str depending if on python<3 or python>=3.

### CODE REVIEW

**Comment by gst** [comment]
grrr

**Comment by ReAzem** [comment]
hehe!

**Comment by gst** [comment]
rhaaa

**Comment by ReAzem** [comment]
Wohoo!

**Comment by ReAzem** [comment]
@gst thank you <3

**Comment by gst** [comment]
welcome ;)

**Comment by ChristopherRabotin** [comment]
Haha, reading this comment thread by email makes so little sense. 😀

**Comment by ReAzem** [comment]
Haha, Indeed that must have been complicated to understand. He had to ammend the commit several times to make it work.

**Comment by gst** [comment]
This wasn't funny on my side but i understand it was from an external view ;)

**Pull request merged**
