### PR TITLE
Pythonic: `x in dict.keys()` => `x in dict`

### PR DESCRIPTION
**Pull request by gst**

### CODE REVIEW

**Comment by ReAzem** [comment]
Is there a downsite to not using ``.keys()``?

**Comment by gst** [comment]
on python2 this uselessly call the keys() function, which uselessly creates a list of the keys and then return it. and then the "in" operator is finally applied to it.
(on python3 this uselessly call the keys() function, which uselessly returns an iterator over the dict keys).

otherwise it's simply the recommended/pythonic syntax to check for a key in a dict ;)

**Comment by ReAzem** [comment]
Alright, thanks!

**Comment by gst** [comment]
> Is there a downsite to not using .keys()?

last but not least : 

doing "x in dict.keys()" (in py2 as well as py3) is a linear search : O(n) 
while doing "x in dict" uses the dict internal hashing : O(1)

**Pull request merged**
