### PR TITLE
Dump directly to file

### PR DESCRIPTION
**Pull request by CBarraford**
This adds the ability to dump the results of a query directly to a file instead of storing in memory. This is usefully when you're pulling huge amounts of data from influxdb (ie several GBs). An example use case is a backup script that backs up influx data directly to disk.

### CODE REVIEW

**Comment by CBarraford** [comment]
on second thought, maybe this shouldn't be apart of the `query` method. Maybe it should be its own thing like `query_to_disk`?

**Comment by ReAzem** [comment]
This is a use case I did not think about. Thank you for your contribution.

>Maybe it should be its own thing like `query_to_disk`?

Yes, I think this should be a separate method.

Make sure this is usable from the outside! You have only modified the `_query` method, which is private.

Also, tests!

**Comment by CBarraford** [comment]
next step is to write tests, will get to that soon.

**Comment by gst** [comment]
@CBarraford 
if you check current master version and even more this branch/PR : https://github.com/influxdb/influxdb-python/pull/136,

I'd propose you add your test within client_test_with_server.py:CommonTests (class unittest.TestCase) (which is in the PR above)..

**Pull request closed without merging**
