### PR TITLE
for write-204-status

### PR DESCRIPTION
**Pull request by weiyoung-zhou**
InfluxDB `0854913b668f3028280553181d684032061999e7 ` commit <https://github.com/influxdb/influxdb/commit/0854913b668f3028280553181d684032061999e7>

### CODE REVIEW

**Comment by ReAzem** [comment]
Thank your for your PR.  I will test it when I get to work and merge it then.

**Comment by ReAzem** [comment]
Waiting on this build: https://travis-ci.org/influxdb/influxdb-python/builds/62391515

**Comment by weiyoung-zhou** [comment]
^ ^ , thanks for your response.

**Comment by ReAzem** [comment]
It looks like they still return 200.

**Comment by weiyoung-zhou** [comment]
it seems so...

**Comment by ReAzem** [comment]
Oh. ``timestamp`` was renamed to ``time``. I'll fix it.

**Comment by weiyoung-zhou** [comment]
it always raise `InfluxDBClientError`, like this
```
  File "/Users/ones/.virtualenvs/ones_leyo/lib/python2.7/site-packages/influxdb/client.py", line 364, in write_points
    tags=tags)
  File "/Users/ones/.virtualenvs/ones_leyo/lib/python2.7/site-packages/influxdb/client.py", line 406, in _write_points
    expected_response_code=200
  File "/Users/ones/.virtualenvs/ones_leyo/lib/python2.7/site-packages/influxdb/client.py", line 277, in write
    expected_response_code=expected_response_code
  File "/Users/ones/.virtualenvs/ones_leyo/lib/python2.7/site-packages/influxdb/client.py", line 257, in request
    raise InfluxDBClientError(response.content, response.status_code)
InfluxDBClientError: 204:
```

**Pull request merged**
