### PR TITLE
Convert NaN values to None in numpy arrays.

### PR DESCRIPTION
**Pull request by georgijd**
This allows the default JSON encoder to do serialize panda dataframes. Possible fix for #195

### CODE REVIEW

**Comment by aviau** [comment]
Can you fix the build please? Flake8 is failing.

**Comment by georgijd** [comment]
Hi,
I've been buys the past few days... probably doing this tonight, if it's okay :)

Cheers!

**Comment by georgijd** [comment]
Hi again,
 
The build failure is not because of code issues. Could you rebuild it and see if everything is okay?

**Comment by aviau** [comment]
Looks good to go!

**Pull request merged**
